version: '2.4'
services:
  db:
    container_name: db_postgres
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PSWD}
    healthcheck:
      test: "exit 0"
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.168.0.2

  pgadmin:
    container_name: db_pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PSWD}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:80"
    networks:
      app_net:
        ipv4_address: 192.168.0.3

  backend:
    container_name: app_fastapi
    image: pyfastapi:v1
    restart: always
    command: >
      /bin/bash -c "alembic upgrade head
      && python main.go"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      app_net:
        ipv4_address: 192.168.0.4
    

volumes:
  volume_postgres:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1